// Package provider provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package provider

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptc9s2Ev4rGF5nmlxFvVl1Gn/puHbaU852dIncTs/xeSByKSIBAQQAZTE5/fcbAKRIipDtdnJOZu6+",
	"WSSwu9i358HSn4KIZ4IzYFoFR58CgSXOQIO0v2aSr0gMchrPsE7NkxhUJInQhLPgKLhk5EMOiMTANEkI",
	"SMQTpFNAotwY9AJY40xQCI6C0fgAJt8fPgvhh+eLcDSOD0I8+f4wnIwPD0eT0bPJcDgMegExkoXR1wsY",
	"zsxOsbUj6AUSPuREQhwcaZlDL1BRChk2xmV4fQZsaSw9POgFGWHVz1HPSNQgjex/XeHw4zB8fv2k/CO8",
	"/jTsHY421fOnP34T9AJdCKNbaUnYMthsNpUq65oXUnLZ9cjrn0/Qsx+Gz5BxKyWYaQRmJZKgBGcKgp45",
	"jQCpCSi3X2NCu5L+lmeYhRJwjBcUEKwFxQybl0gJiEhCIqQ50ilRiEdRLiWwCFoOn6eAvjUu/BYlBGiM",
	"iEKV99Ai1+gWK8S4rsIVd09twqE0NpK70X89RRISsIpRwqUzZmudO/ge2wb2rRo8MCkSLjOsg6MglyTc",
	"KvXZqzTWufL4cz6fIfcSRTxuWTMZDreSCNOwBGlEaaKp59xvUi41StvxUXmWYVk0CmBBIWsdecpWmJIY",
	"TZnItc909+BuN5e1VhC2tIqck+3Opq5Ua6GOBoM4yvrl037Es8rrxJkSktKUh7p30yy/q6BU6/x0vV3N",
	"F+8g0uZEVQPpnurnnNJtmzDVwXMZAZIgJChg2mZ6p1giCVjDjSaZx1FzkoHSOBPoNgXW6kM20xMilUYS",
	"lkRpkDbbt+eOsYbQijUnxPErRouqwXTiFBMlKC5uXHe6p3DLxcgsLotkT3/8e76AX4nU6A3IFYkAzepV",
	"HRuAxYITpvd4tnqNLl+fGXdIaPvjeDY13QBHEShFFtSfPUqMWtmDBRmsRpiKFI8Gq2wncXxmpoCpTm/2",
	"FqV9XZXlXeBh/Fk8JDgkfghOVYHwuPoPA9bnhZ17D5iBxjHWFvG+kZAER8FfBjWKD0qQGlRHOq/Wbyo8",
	"3eMem6FlDO70y/t8ASsidTgaH/iCbirW1q8n4mdEaaOkXoNULgSXGuIGhpTqd/vaVdkBgl4QAwX7Ry5M",
	"8Zr2QzRkVuWezhpgKXFhfgsvnXlddSHzupEtrcNX2flg6Lo3oC5gNyuQytrRwRv7HpXvqwg1XeRCNqs8",
	"qVoGVwUbtJJxdWVS7rsn9t2/F6Dx0x/to79+40VVp+3GD1FzYwNPaptMDLe9hieJ4ZMtmzKfEhfJP9nd",
	"KVYaOQl/trPvoJstlkan3fFCJ3AdAOwF6xCDCCt0cwTbhkAZBXUqfar+vCHxxggSNJeYNtPN6CNsmVMs",
	"G48bbnS2VS/6BvkJH2wXbhpwbIqw6+EZXhJm3IdoWaRN5W0gZrDWNwIv4Ubz9+BJ2rl5bAtagpYEVhVh",
	"MTuR2WkUSFA53clXKF6Kf55MD6fvXhTn48vhxfz3g7PfLievfpvq8/nL9+fFKL04vRyfzf9RXLz7fX1x",
	"+uLg4vT49vzk5XNfVtWHOPpUt4iHdM5u59jcwXHOG30ZxzExjsB01nCbS7q2n463K1HV2BFe8FzvQmHb",
	"/4bFcHZjiWzH978AX0osUhIht84SXh8NcF0Y2gHIVQhY6XDk82aVy/c6sWqmJ1jgiOjiLm5+Ym8IugYF",
	"TB/CCRy5KHxmfuTM45jjFSYULwglukBmCeISGZdHwDTIfS2/XhEuvJy4kxOdw+/HmqhcgghzPcvHezXX",
	"mN5EIvcVmsYUncwuUcQlKITdGduMbrzngmPFZpBxWeyT7N76xQaj+U/ei4yVy7zJ6aSyPFu4cYFZ1cq/",
	"0V22Ks0lXu4VW77eY+3YZ203fBbuolwSXVjodSFYAJYgj3NHHGyWm03ucS3WUGc3LDDxtHcWzjSOTL/d",
	"7Bb/6cl5h2lZah6i1/aa4qoBYRajDDO8hMyWSdLZpfpv2dygriX25rxmpfJyufIKVMpOKL9FWKEYEsIg",
	"RsRi61tmbAOWmqu/VWoSkitM+29NelISAVM2DuWM5ljgKAU07hvOk0vauEbc3t72sX3d53I5KPeqwdn0",
	"5MXFmxfhuD/spzqjjTt34HNL0Au2JKmmNY5wMixIcBQc9If9iWM6qQ3boNX+l6B9pahzyRTCW9yr74hb",
	"SrMVg26JThEXZZtKCNVgM6nBe6dxyXRnTQBtjNauOpc2K6ahZVHskmA7F/uQgyzqwViLiHiY76a3q+gc",
	"r0mWZ40CLDEYCaPf1JZfVYbXDvAV+djWGUOCc6rLys2cguoXYeWvbk13jatJg3BcxPVCnzkN7nHX+a8t",
	"YtnJm02A8XBY1SS4yzMWgpLIqhq8U45/1/IeQhMsm7Ilv8Pbc3u7TnJaA5vJ1smdNpSTo+/+mC1uHOkx",
	"4icc25kfKAtM21g9lv5LBmsBkWGVUK7pBeWwrLoO4sYoyFSKxssWPw6uDY3jylu7rlIRRgxuO9Vq8N3d",
	"CRBmCNZEacNDOYP+W9ZqsUQZ9M8ENz45estCNE3cjTjm4Kakdnuv1PRmhoBpWZiN7k4aNzfZtWWvUDiD",
	"AeNbo6anPTe6q/aXt5Z9+2OS2IGcbkloN3FMqEJPIs4SSiL9tBRVr98j0Oi6V1Sns53Y8zZGA3e2tldV",
	"q9wGZXpqa7z2d8uCPQVP4uDxZv3X7iYISv/E4+KzdwxXKO0PGZtH6FS+At0CbJmF6ImEsBmPp6ZvjIej",
	"x7WmrCn0xBRbx5xHbaHV3N4Ny63254+n/aQsRBSWAzrZLGtM7WDUsLZcgTVuPH484341jnF9A9YRiAri",
	"vjaYacCEb7jexZtNr8Ec6/HMNN44DLKzRw8aZXwFCHdxKJE8s02/TOWi01RPrcz9TdXnlnrJYOdTrYf4",
	"TDwTn8o8d6AYqS1locUXq7PpqR1kUgKxs2HyeDZsPWIAP+E5i7/GdHa50sizu5O557/3/ALal6qLAhGt",
	"UO4+CkxPO5n6C+j/Ypo+Dup9Fdz8/wn/0IR3qSruyXIDz92PW136v5vydnYCTVgl5QcGrFOU5UqjDOso",
	"bQlpbO5UyLEQtPi8NfI/Ska/CkBqEL8vXplflHu22aZBCsy4ThuDq6+xeVQd4KHUrzH/teXanPxeXZty",
	"NA2kKmY36mz9a4Qt2VJy52Pu7lyzOdetv5t3/vUt2Fxv/hMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
