// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Frbcts40n6VLv5TNUn9OtoaZ+KbLY/lZJiyHa8PSWUjrwORTQkJCDAAaEmT0rtvNUBSJ0pxshtvLvZO",
	"JED0Ad1ff932lyBSaaYkSmuCwy9BxjRL0aJ2T6E0lskIw/iC2TG9idFEmmeWKxkcBjeSf84ReIzS8oSj",
	"BpWAHSPw4sOgEeCUpZnA4DDo7u1j77eDZ038/fmw2d2L95us99tBs7d3cNDtdZ/1Op1O0Ag4nZyRvEYg",
	"WUpf8kqPoBFo/JxzjXFwaHWOjcBEY0wZKZey6SnKEWl6sN8IUi7Lx26DTrSo6ex/vmfNvzrN57dPih/N",
	"2y+dxkF3Xr5/+rdfgkZgZxnJNlZzOQrm83kpyrnmRGulNz1y+eIYnv3eeQbkVsGZtIC0EzSaTElDHsm0",
	"ylBbjsZ/bxkXmyf9madMNjWymA0FAk4zwSSjRTAZRjzhEVgFdswNqCjKtcZ1h1+PEX4lF/4KCUcRAzdQ",
	"eg+GuYUJMyCVhUyrex5jvGl1o/J9ze1fhqAxQScYEqW9MpV23vAturXdqmk/MCgSpVNmg8Mg17xZCa3T",
	"11hmc1Pjz+vrC/CLEKl4RZtep1OdxKXFEWo6ynIrauy+GittYbx6PyZPU6ZnZQJkWg0Fpismh/KeCR5D",
	"KLPc1qnuX+x2c5FrMy5HTpB3svtyWdbY2swctttxlLaKt61IpaXXuVelyQtVHure+XL6vQ8Ksd5Pt9Vu",
	"NfyIkSWLrlDf8wivZxmGW+PoRS4EGL/TWVLBB2WNyrX7kWk0KK3LgI0kijQyi3eWpzXnX/MUjWVpBpMx",
	"yhV8chmQcG0s+CPiZWfEzGLTnUlms/i1FLMSdTYuL0aBJPBuWwD2iw1lEFLCxORqysbya9OCoyHZ6ZZZ",
	"ZPk9DmSprmnB1fGfJ/2b05M+cBnziFk0qxZxA59zzDF2J0QCmcyz1kC+OAo3vyqWYcwM4DRCjDGGlE15",
	"mqeg0WqOpjWQFyfn/fD85d3F5es3Yf/kcofsCeOWYpOEc2sGssAWTWA1xEilCGNkwo5nMMRE6YUSDp1I",
	"ZNwa0BWjzFOKssrkoBF4K4JGsK4Shd9X74jHD6lhHskQiuAFil4I/42K9p+tS1+1Mqut1ZdlKtHykrkr",
	"BhVZ2KQzm+W1PhSjv65YEQp3vqyva3jOUlzCT7d1RbtP+RDvubbN7t5+LfRnGNGxLI45ncnExRJKeKXW",
	"oLy44rJm+fqaKCHUhKJYyUojk2eZ0hbjFagayIITwJM3Z1cZRg04VtIyLlH7xz6zbMgM+iel4VjkxvrV",
	"pz7QN2BzG4RceeTYRbIuT4767x5yGXkWfz9kCmYs+BO+FzHXSslqbBR3uVFSGsG0yTBrlnXBU1aXQIZO",
	"qY1f0/5S/rzj8ZxOzUSumdgW8CSey1EumN6xpbTHL5f6t6jictWu/2peXxNPubGbl3DBRlySh0FwY+nW",
	"K4s2CuBihR4spu7HLxqT4DD4v/aC5LeLeG3XleaKgwRMazajZ4lTe5exEd5Z9QllTajQa4eZHrzvS2ZC",
	"XwJ9SZprNLmwZiVUcfYq+8dxeBB+PJmd7d10zq/f7Z++vem9fhvas+tXn85m3fF5/2bv9Prvs/OP76bn",
	"/ZP98/7R5Oz41fNaarKWR5RIGOWa29kVGe2dM0SmUR/lHiOdN+gj/3pxLBEoT/q5TJTjGJTXEd3TfB1G",
	"+sdncHUBFcSeMclGmFIZP7oIoQnHRC4IWpik+lqtqqSqMivEh4ruNZFp+pyTv2i72V6WIBFqAswQo+AS",
	"Y+AuaweSVEM5pj1OIoWNMkx45BE8QmpKDr+UrdZRxqIxwl6LED3XYolLTiaTFnPLLaVH7eJb0z4Nj0/O",
	"r06ae61Oa2xTsUSdK4C9KNLjydXF021+ChrBPWrjXXrfZSIbsy4dpjKULOPBYbDf6rR6gS9x7jbr88wt",
	"jdDWVUGba2mAVTlVSzwNTLgdg8p8GYGEC4suzpw22l1mGAeHAaVuuJyWSw30+w2m646pRC4VOdf0fs5R",
	"zxZd79LyosfdiPotMhaWDGcrNm4RVmy5K7Z8g8AwAQfwYFRim47Iuvgr5TNNfo1EHldhWcLBQDKh5Mjw",
	"GAuuu5QB0MeE0S5ijgkTBn3M1mo/VpO7QvSK9rE/Izh0B1TZPVSKSGedOWcF+5V5OvQDjUJZyFA7PNui",
	"Q8qmHigN/wvrlehSn1nQ6/KJy+JpswPdVG4BtpkvDr4Zqo2eBWbvuk5Hm/1owmXNXqdTgh1Kl0Asy0TB",
	"jNofjZIVbLLvKDGu0jlYXWM2eRShMUkuoMovSv3eTnWKLvv/v00tP7qpUeIPFrv5CBrrO7ri2h5L/o3E",
	"aYYRpQ8WexpBMVgooAbYtl6ZwMeykaNBFd+4Jdat6siFq0gIDCROFtxOJcBWjm8N5OsCBMWsoMkzYBAJ",
	"jtI2mTF8ROUm7A/kPWcuuT/w+AO4aIQKDVsQJiujpoYvTyQLNUy4EDBCSTePwCSEfZ/sq2DrlV5qxXai",
	"bak4hH2XMrVu25I9fBVGfuxk8dZTYTT2DxXPfmT6+ahbnaDONxCg++NVWCshZfyVQ5jHzvxyNOfnYU56",
	"7/GknysLicplYffzx5N8rGQieGShWSVE2AcmqHebUbHOjesKent7j6fUG7oKT5dxGmFW1oKfDY9LCJU7",
	"8LMelOeNbcR10aqG8dyjNpGaOiKbqvsV4S14S736h3Km+AG4KZhZOV2EhHGRa0/KBlJjpHTBylg1hnPT",
	"Q9eoeKbmgImaO0ecjS/ULXDtCTcDmRuMIc4Jy0DjeBbrYooi1MRxN3aveAxDoaJPfqZSEV/vVlMH9W5a",
	"ugPq6y50saW99perTSblfLXDO4vRLFmw6hw/kEUWe3ZIjiHDmPT2tOBml0u2s9hS5Lcx2E0G19sMlwph",
	"S35uKsIlZv81uA37bqwmeAn5vcfUofCIXEbfnw1jfBosp/k2mlfb7r5Eu4JPwxlwayD3M++wv5F2L9H+",
	"uJx7SKfo06l4XaRYr9NrDeSjtIOP3A79tK3Q/zL0oRm6nmJrI6UtBGBpNulSa3kq+f6WwtB3Rj7x/Byu",
	"zTLeXszFbquTN/5MUD+KrKLJbP5nRTC/nf8rAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
