// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3pcts4uuiroDhTFbuHlLXb1q2pW25b6Wg6XsZLZm5Hvh6I/CQhIQE2ANpRp/z3PMB5xPMkp7BwFWXJ",
	"jp1MT+efTGL59g0f6M+Oz6KYUaBSOIPPTow5jkAC138dYolDNhtJiEbBGZZz9TAA4XMSS8KoM3CuKPk1",
	"AUQCoJJMCXA0ZRzJOSDfTEZEQuS4DnzCURyCM3BEhMPQu1UPiVoiVgu7DsWReusX93Rch8OvCeEQOAPJ",
	"E3Ad4c8hwgZWKYGrFf7/e+z91vT2r7fsD+/6c9Ptt+7T59v/98+O68hFrPeXnNCZc3/vlhCkQmLqw5ch",
	"iohd5okYZ0C8NOYXwG+JD5eL+AkYCzMZ6WWLiK5CURR3e1nU7tXqImZUgJbhg5ADDhbDT0QYEfcZlUCl",
	"+onjOCQ+VvjufBAK6c85MoocEpPQGRSJhe6InCMSoFe3kaeYFWAevELY7ILAbKOIYOVg4DT9/u5s3p97",
	"u7Df93Z7PnjQme950Jr19zrzaXd/T5FKSCwT4Qy6zX3XkURqgp6DYAn3YXkDi/fB2/PhwdH/uxn+c3Rx",
	"eeHcF2n5Zw5TZ+D8aSfX8R3zVuwMOWfckKvMdUsvZAl27zo/4uAcfk1AyCeS7zWBMECvrBDcKMhfoSgR",
	"ElEm0QQQRLFclIm2u9/pBtMOeN1Jv+N12/sTb9Kc9rzJXtDpNcFv9XtQIlozJ9qI3uKQBIgbqFHBqGV0",
	"G528O3g7Oro5OP/p6nh4cvkMlPsRBygl1L3rvGZ8QoIA6BOpdiWAo4CB0FSa41tAMfCICEEYRZIh7Psg",
	"BJJzIhC3clIm4h7u9mDanXo9f7fr9TrY9/zWtO/5+9Dtt6ZBe7c/LRGxkxPxwKw+zbDISHc2PD8eXVyM",
	"Tk9ujoYno+HRM9AuJ9a967zBIjWET9XYgmGvaOoci8xIv4SiVte3RHt9MHo7PLo5Ox8enp4cjS5HpyfP",
	"QLY3WKCcVPeuM6LKeuJQWSzgZt7TKHhAUULhUwy+hACBWgkx3084hwDdzUkIKOZMyQihM+0VrLqVadqG",
	"vX3yYe+Dtz9r7Xn7uzDzZr0PTW/WIXvN3od5v9X8UKBpr6zHBhntb4AbIIoqfDk8Pzl4+wx0zHYydEN2",
	"oOucMPmaJTR4BsdRFsNMsbVBL9Nsf9LrT2e9mdcP9npevzsJvKA92/WC5rS3255BZ293VpLDbo0cqrWn",
	"GvSMYCenlzevT69OnkNhT5hEhjL3rnPGQuIvjiAGGgD1F0+kllkGwS0OEz0aicT3AQII0CSRCKM0bkBB",
	"the6w4aQAksipgSCMjE7frcXQH/q7c729r1ma068D+1O1/vYC/u7exHdb7ZYkZjtAjEtQPlmL63PdsMC",
	"JTPqnsMHrYpPpK11TIjbZdBkgexuQzojtOI5WrjdmfjdwOtBf9fb25/OvHmz1fZI50O31/8Y7u7tRyUR",
	"7C9RLd3pK9Eso4+iGGe3JPgy+3dxdn6sLJxeKDM9Rcs26XT9oAdef7q75+03Z3OPtNod70P3Y6+/G0Z7",
	"+01aEqx2gUTVdV+WQulumVm7ojiRc8bJb08WqHc6xFLLqPTATEA+B50t4FAgzCHX143Clb7f7gTQDrwO",
	"7rW9bnsPe7jf7Hl4N2h3m8Gk2esGJaFrFcKVMiBZgpGR9urk4OryzfDkcnR4cPksMUuJiPfZetXMWWc1",
	"nMXAJTHxDI7JzS1wQQx1y6u+My8Qm2qnWgxkzPqISAHhFG1BY9Zw0W0Lh/Ect7YbYzqKokTiSQgITyVw",
	"xQ5NjsaYltM0O8dxi/nW7XuVVf1FpVfXfzG/axIs19Grwo0kESyDf0kiEBJHMbqbA13Oj5W1NgsEaOv8",
	"9SHqdDr72yXo2s1232u2vFbnstUdtJuDZvMXx3WmjEdYOgMnwBI8vbtK9XBwSsNFmkguARsQEYd4cWMS",
	"0aUUVwD3ppwADcIFsmORGlub3TfG9DglMA1yH07BiPgEUKKT5irBLyIchugIbiFkcQRUonfHjutE+NNb",
	"oDOVfPc7rhMRmv7ZqkElrs3SM4evXiNiSG5oNUiB9xTwYudzqbZyX4GxPLZQsiiISHnMZgn6WhaJGPx1",
	"SlhQgws1/N51EhI8tUrTQJfKCk11XkoEYomME+kxGi4UY8eUrFIkdDkHNDpCPqaK20zvi8NwgRQWascA",
	"3RI8pr8mwBd55omMcdSL/B9EplpsrHcJ3KyoAhzNgALHEgTC6OpqdNQY0zF9zcKQ3Ql0MDzzWu12Zj81",
	"KIzeKmwZFVWx6/easNdtNj1Q+XO3FXQ9vNvqe91uv9/rdbvNZrO1TgwfXZBZy+8kDr7MfoRYSBSxwJB7",
	"AyvSG7S+xIrcZ0/YRAUZjut88jDEXubG8sKVcAbvnXq1u1F/3pDg3rl2nThMOA6raqe8G6GzJMS88io3",
	"xOnTCFM8A94I/KhB2E5p8Ira5rO5onTB7y7pW7ukrNbwu/ZNXlYxKTuprBz+kLMqTF7vtQqDv437SnF6",
	"BjeW8/67P/vuzx7lz/IDmPclH1CxTla6r7/EAdbotvWE9vmDLtEr1lJX+EavcOi2uZPMZ63wlm+JOfEo",
	"e0wKn+RNjGdwI9lHqPGal+qx1lcOkhO4TeujaiZSMxtjOoxiuUCGIYjQQOWtYJNjIvRwLRV2eEkSYPG3",
	"21+iX3775Z9/J6cfru6mf//rX+ucIgeRhObMq3LEwzleKK9ea0wyZdTVcR2VPN66OXnMhNVuS0KXAucu",
	"EXRJ2Oq5c2HNbhm1C2O1bBVAMQHXY+miAKaEprwpjeEwBQ7UhzFVrtSYVZ/RKZklHBcsU1kyKmFejWTk",
	"QZTZaHRkOL6KDxYM8Zg4Svm+Nc46ZfANCcRjfE9mpa0nPwuxDzpiOLZqNqYPOiIkQKLJougegkSrQBmd",
	"TOoeZfrbS5ivNd0rBliRdZ1EAL+5xWECD6mRGoXMKEurVTytoPeQUqk48J1ac60qVeWuDPYadfqDGbkv",
	"sW0vZ9OeZssaaHirgrISggH4IeYgxpRRQIyjiHHQ6UOQI4+2/pX9/peLIkJRa7uBDpBysCFkbn1M2XQK",
	"mn2JAIEKs0wfhNoDqOSLOnuY03oJtZMyPA00xP7crJRhgHCpz8TNgtMxLZz+MB5oAF30sKl+DLPTtEVx",
	"KSJ0ZKa21nPfovsAt88LAVNFXitM0gQmtMrzGjprpB/SgDqq5IYq3VAprOJCaZzxkiDUUyE5JlQKk1/C",
	"FCth1+sYCMbU+oUi29I8wq8z7w/xQjeNHBZhWda/tL9oUxdWwDYlb9X5j6ktYmjBEkcTF+E43q6ap/Tt",
	"Js5Wi4i4WaMOQnGKybny7RaeXF/lHEvTMcNB8ehct+gIiSWM6QSmSsfL6BFh0jEV1UNQAf99Dv91gR1r",
	"MKnSvtjPUx/sXBQFoU7gHohqtm4jV0mdxIQCd1GAJZ5gAS7yw0RI9UhIxvEMth8fA1VUN811igjVKXF2",
	"nlhGVT9GadcZmurkVhlNlcnt7jV30RlnkxAidKRPz4zSvLm8PEMHZyNhokydCu93zBkdOk9b2Or0p6z+",
	"6YlcFao3SYSppyIcTWD4FIeY2mN1uyaSzLDENnaoqNMW+/TBZGNMj/Ei5ULa4OFl0wOLjmRoDmGMApgk",
	"JgwgQixXmjbuA1sSPVIoYG6s6hmYpeYVE4UdmnpHIiAwEzj2PyqWGds2SWYzQmdVBDZsSsty8oQTL4vi",
	"6/BKjzKXeKdkw7xEPgsAbUVY+nMQaRxuJM2MKNUJdCNcBgChstPONyZUwgz0CbA9N12KOeaMSxfNy7Ij",
	"kijCfFGSDa3UjTG9mLMkDBQxlYsgQqp8APuciaJYiXSuwFFlgRKFN2ndq1qkKg7H2J8TCgXR19spOjbQ",
	"ldKpg6Gmrm7FKbxN6000iZRVWGoRdJcOkd1CT41b7cV0azrlXOd8eHF6dX44vBn+883B1YVZpe7c33UO",
	"fjw9N+9Pry5vTl/fnB+c/DTUYIyOz94OFVD6ddYJpSF8dzB6e/DjWzXwaHhw9HZ0ojY7HA6PhkfKrBWo",
	"vYzhprJbsaC2E9jKcypedTa0xq8vpR82uFhm7ZF5YZKtXNN1/KGST+VnTHAoELPlZvXulUhPKrZspdPg",
	"4SKaRBPlSyaMhYCpiwykLtJuTp9gTBEERHupv05xqDxQMYOZkk8QGIAqg3VKWRpLKJEEhzsimc1AyMK8",
	"ohK0XYcmYajWMHmp7jzQSN0Yaj0ubjLdROKUbnr4gH1lCUM8gbBCY5X5X412Dt+ODK4sIlJC4CIVhN8q",
	"W8pZpFHVFX8bSo2dWz9OGj5LqBw76H/+67/R2Hnnxwk6NI+WPPjh2ZV5t1zNXTICKb1LgmMYVcHuH3PQ",
	"8RXQQOfsQpe9deF1UUTSSJeu11o7pOhh3ZYwmGeSAHm1w4iC9qmQBsi1HC4VG6zkrT5FOWLSo0wa163p",
	"KhnCOUPWhtzDxmxQYYJiSgQR44uGIL/BzWySPpNYRVoNzX3RkAT42KnGV9lC68Nfbc41IDd5uw0OAmJy",
	"ubOC3huqlHH/28XpCbowqltMQZRYpkvrykPGvK2A46lE7Wa76bXaSrJOdfXJtDUpd6AZW9JS5caSOGZc",
	"itwvFLf+CIs7xgMxsKloRCiJkshFEf6kf4ypLX+7SLkPPcKQRY9Jf4L09fnHeWpYB2guZSwGO7rXyjMk",
	"ajA+29Fo7Fg0im+9nKRlvixlFdq0Kcer1MlnKqfeanmt/rbRKgW4M2j1NQ/tH64TJaEkcQin0yJDi5FD",
	"2aJXHIEW4c3sfm6XlkA/ZDSVkEyRVAgXm4y+cNz1Slh1LZh9TE0elboFD73WSarSTpOqDhBWMToEusIm",
	"3v98nZrodDctJIWW7p+zdVLJWbsUTvNvC3btmucgWKgspx8SoNITJACk8pxAYaIriwJC8FdWne3uhSpl",
	"vXZ9zvK8mlSuGkDFxpBbWItWccuW8z7CAv28rSxRit2SNx5NC+YRS2O64NcEh8JMdwvjX4lsIcxBDS8j",
	"9v7n69TBE4EiHL83gFy/v8Z0MVALmpnmsXDTgqxeTeGpQ1BMF8YrpeO0WGkhFdYLLUnuI6xyjq9Jq2hR",
	"LhsPmdGHwyt7m6rC6zo1K3Scf1m3R9mj2OCp3N+hfk1Amh//vs0eecnncY0ezUHnyxo9Ume6zAjjXR9S",
	"1uWukRKaP8PCMwoZY8KN8vlYwoxx8puRSVMPDaUujzbG9Ecm51ZNaFDUDqsJjao3sestnIFDQd4x/rFc",
	"CCp4gA115sF+ECtwnlpL7HwuXRm8twdL1rL6mDJKfBw+dEpVFbry+oXLGGUpLA97rh6RB0tlhyEWIq/0",
	"1yhgY0wPWRQxmvKNUD9MAhigjatkjTE9CJSjVzGUZFwZ0YUt7yI/EVIF7gpnNIEFo8qCgYDa0trKFpjN",
	"4zprpvJSUrnqnNqb1AZuN3IBwBSxGP+qXD7RbhHzrERViNM1Mvn6xlnr4GtosBFosigNHigP/+54gJRh",
	"dpEJjzP6uWimMoEbJlzbyq6GH6akHyAS6VFZ0dZN70e5yKqPmnBkGTRAoK9duMga5MJMvbBh3yB/TVmg",
	"AjiFKWchikOsZqt1gYttNefCQDpAPo6xT+RCYXs51xqe+DLhgG4xJwrzNMAoCJoWTnNKq6mfeoolu2AI",
	"o37Z1MEZ7Olalt5dizcRH4UzeK9siIFEj+o1swvBE8aKXk8Ezv21yhb8ONGCxP05kaBhdgbOp73+Tb/r",
	"uI7xloP2vTmZKUpZq8YKPbK3qqRx31uqfkctVSUX/+h2qvag23updqqS5X9qO1W9a9RrLjVPlcaWe6aK",
	"r9a2SpUGV74Y8GJNA8r32VP0x/cPnBqvoDdHHgqY0SDMhT4IN+WDxJcowjRRCvlwz8Hw7vhN84k9B6Xg",
	"OT/mNscp6UGH0fEUX6Qr/BopbRgecVRajPmft0chb0JZ4vbTa1UpPV6JEp3GtFy3Qqmf3qR29YjUKu9/",
	"eiBA1f3WWtBMlC0xn4EUTz8Gvk2pWEm6yoXsvJPoparZZSO4sonBcdOc0wB+XRf1C/ATTuRCF8mMVEwA",
	"c+AHiZEN89fr1Kb+7R+XzlKB7x+XVmPZREdShRpyGhNCgNSKKL3H6NirdjqQ0FvkXJ5LGZvLeoROWXq3",
	"EfvSFD6Wz6iPDo+zpjzbxoYOzkap59VtKDZRIL9BgO7wQsm0sZZjWtJ001Joqxg0KDUWmByN0CnHeThW",
	"qCnbAFdtPc1dOdpSD4Z0jqlttVMxDxM4FNsZXHrpMU155zFOgEp9S1qQGdWL/+lP6DyPL1W0+MMPBbsh",
	"fvhhgI5MMiAhikNtaRXEAZnqWqW02QGbrkJiTBHaene8Ih/5OZkAp6CWraYm6JaFSQSuttKFTGTbgFlo",
	"lNJgHqosAYLMeKQ9SsL0JJVD/krbi4JRcyavJWudCIkPVGgFtRHqQYz9OaB2o+m4TsJDK1tisLNzd3fX",
	"wPq1rtTauWLn7ehweHIx9NqNZmMuo7BwzuqsEDOlYGlBJi+L3LsOi4HimDgDp9NoNrpWH7WO7azojx58",
	"dmYg64yadrZalGM8I1RTLyRCruwBFsWKeFZEUAlTfauqjkEdDbUh9ChwBo4KE2o6d4VGJv/O1PsvihPS",
	"Dw5pp5l/cajg2IoXfZdCt+XDY10Xt5ZUS7tWXqkctUw4RTFwDcOKjSP8yXhV5ZtKe2eHU63aM/q8It9U",
	"74s1+WoRfhns15pHK5i5xDfNLn0sYnASFsm7OXBzfNSoNJWivP8g9YlL9ZXKR64qdFnuUl3NlevKN5za",
	"zeYGt9Q3u869qtG/5oL3RaLz/GkSZi0XSjW7Bpq6TTKodwofTdJTWuunlO+Tq0md9ZNKH87pbQJZ3Sdi",
	"tDc3TR5Wb1eIkq7tMVFjZQ51YVXZGAp3K7ufC2ZFxTpenhKPjoRKi7Wev1p1T+QVqibN2qkGEMVMAvUX",
	"dWbIQFZ3SWGNHTq1qXsV1FU28DHqUNGASgr9yG+eXZsgDoT8kQWLl1SV9ANrxc+33S9pa+vlQagIXy1H",
	"0lq/yPQ4XBQU+FkAfOCTQuVOpgkLFijtlUXGmX89y9Bt9tfPqHxoRk/bXz+t/IU9Navd3mCz0jda9Kzu",
	"piCWv4/zTFbPmIlV94X04J3H3Vk1RjIECXWdTCEYc/nARZGyHTNTNrJjdbTIh+ys/uxljevt1tj6WnUz",
	"qNap21cS8Q3kJ/ue1/PJjWHLarlx10fl5trFCr8yWSAixYoQ+yeQX10gmv8e1n2a8vE/XL5+AvmcRmnA",
	"Yb4IVAat447aWO6Sk9kMuEDpWHssian5XJ3Kx2p41xjTnwpHEyoOLJ5CmNbqEGamistW3iFckvLzFOQ/",
	"qqxnPKuzro8Uy++hwFqVy+Rtc8V7jvLL6qpLpRdgXaXle4Xlq1RYRA1rzmsKKpguag49zHm7ravU9lnU",
	"IV89T/zWNZTvtZM1tZMnlUw2r5Q8V03kWWoh/9ElkG9Y+lgbKHyvdBTC9KfEKS9ZQ6gJFqqfYnx8pWCj",
	"AsEXxcZPLgj83uoAG0lM6Zv0L1w8eHLN4BGlgpcRjeY3sX5/3EqAbbX26/57i26hE5XjcHMJoiw1if6C",
	"v77udAx8BuhMdyLpxrndzn5/W0cjJ0yC+Q5BocFN5/RZjp+3BGzxYiONcMt9EsJFy19F2Na96OTBGwRl",
	"gTYYvoRMbxJHRIpUnib+X144pvg2WmV6ML9xTGGAyP61xH++jhuhro0gyp2dTys3rGpXqr0BaacTfRFN",
	"2QhdGNApv1hVhSj2FD1rFaIxpqdLHWKVHkYbcmoTF3O4JSwRWfppGyq/SSXD3IbT/6UizZzc/BM6kqFW",
	"s7kavq9S8HhJZ15tHf5eLyjXC0rOcdN6wQpVfu7Sgb3FOTpCRKy+knBHwjC7l4AYhdVFh2K38hOLDqOj",
	"+jsbY3qcCGn7J9HRyYXXarU7+ZcMIizRVsjugPtYANLddjSJgBPf9A7OF/EcqNiufN2g/u4FzQLtDep2",
	"v4diR6mP/OsWO5a2rr0uZmT937LYkV/Kt//T5Y9W8Sj9T8jleKV6oXOj+MXmuCVLty7HfdC8rMkHlv8p",
	"5tdyi2uF/o+V41aEqXDXQLOxeMvg/bXikbHOhsmmWXsHx2Qn76i+vv/fAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
