// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H35cts4mviroDhTFbuHlHXb1q+mfuW2lY6m42N8ZGc78nog8pOEhATYAGhHnfK/+wD7iPskWzh4irJk",
	"x06mp/OfTOL47gsf6M+Oz6KYUaBSOIPPTow5jkAC138dYolDNhtJiEbBGZZz9TAA4XMSS8KoM3CuKPk1",
	"AUQCoJJMCXA0ZRzJOSDfTEZEQuS4DnzCURyCM3BEhMPQu1UPiVoiVgu7DsWReusX93Rch8OvCeEQOAPJ",
	"E3Ad4c8hwgZWKYGrFf7rPfZ+a3r711v2h3f9uen2W/fp8+3//2fHdeQi1vtLTujMub93SwhSITH14csQ",
	"RcQu80SMMyBeGvML4LfEh8tF/ASMhZmM9LJFRFehKIq7vSxq92p1ETMqQMvwQcgBB4vhJyKMiPuMSqBS",
	"/cRxHBIfK3x3PgiF9OccGUUOiUnoDIrEQndEzhEJ0KvbyFPMCjAPXiFsdkFgtlFEsHIwcJp+f3c278+9",
	"Xdjve7s9HzzozPc8aM36e535tLu/p0glJJaJcAbd5r7rSCI1Qc9BsIT7sLyBxfvg7fnw4Og/b4b/GF1c",
	"Xjj3RVr+mcPUGTh/2sl1fMe8FTtDzhk35Cpz3dILWYLdu86PODiHXxMQ8onke00gDNArKwQ3CvJXKEqE",
	"RJRJNAEEUSwXZaLt7ne6wbQDXnfS73jd9v7EmzSnPW+yF3R6TfBb/R6UiNbMiTaitzgkAeIGalQwahnd",
	"RifvDt6Ojm4Ozn+6Oh6eXD4D5X7EAUoJde86rxmfkCAA+kSqXQngKGAgNJXm+BZQDDwiQhBGkWQI+z4I",
	"geScCMStnJSJuIe7PZh2p17P3+16vQ72Pb817Xv+PnT7rWnQ3u1PS0Ts5EQ8MKtPMywy0p0Nz49HFxej",
	"05Obo+HJaHj0DLTLiXXvOm+wSA3hUzW2YNgrmjrHIjPSL6Go1fUt0V4fjN4Oj27OzoeHpydHo8vR6ckz",
	"kO0NFign1b3rjKiynjhUFgu4mfc0Ch5QlFD4FIMvIUCgVkLM9xPOIUB3cxICijlTMkLoTHsFq25lmrZh",
	"b5982Pvg7c9ae97+Lsy8We9D05t1yF6z92HebzU/FGjaK+uxQUb7G+AGiKIKXw7PTw7ePgMds50M3ZAd",
	"6DonTL5mCQ2ewXGUxTBTbG3QyzTbn/T601lv5vWDvZ7X704CL2jPdr2gOe3ttmfQ2dudleSwWyOHau2p",
	"Bj0j2Mnp5c3r06uT51DYEyaRocy965yxkPiLI4iBBkD9xROpZZZBcIvDRI9GIvF9gAACNEkkwiiNG1CQ",
	"7YXusCGkwJKIKYGgTMyO3+0F0J96u7O9fa/ZmhPvQ7vT9T72wv7uXkT3my1WJGa7QEwLUL7ZS+uz3bBA",
	"yYy65/BBq+ITaWsdE+J2GTRZILvbkM4IrXiOFm53Jn438HrQ3/X29qczb95stT3S+dDt9T+Gu3v7UUkE",
	"+0tUS3f6SjTL6KMoxtktCb7M/l2cnR8rC6cXykxP0bJNOl0/6IHXn+7uefvN2dwjrXbH+9D92OvvhtHe",
	"fpOWBKtdIFF13ZelULpbZtauKE7knHHy25MF6p0OsdQyKj0wE5DPQWcLOBQIc8j1daNwpe+3OwG0A6+D",
	"e22v297DHu43ex7eDdrdZjBp9rpBSehahXClDEiWYGSkvTo5uLp8Mzy5HB0eXD5LzFIi4n22XjVz1lkN",
	"ZzFwSUw8g2NycwtcEEPd8qrvzAvEptqpFgMZsz4iUkA4RVvQmDVcdNvCYTzHre3GmI6iKJF4EgLCUwlc",
	"sUOTozGm5TTNznHcYr51+15lVX9R6dX1X8zvmgTLdfSqcCNJBMvgX5IIhMRRjO7mQJfzY2WtzQIB2jp/",
	"fYg6nc7+dgm6drPd95otr9W5bHUH7eag2fzFcZ0p4xGWzsAJsARP765SPRyc0nCRJpJLwAZExCFe3JhE",
	"dCnFFcC9KSdAg3CB7FikxtZm940xPU4JTIPch1MwIj4BlOikuUrwiwiHITqCWwhZHAGV6N2x4zoR/vQW",
	"6Ewl3/2O60SEpn+2alCJa7P0zOGr14gYkhtaDVLgPQW82Plcqq3cV2Asjy2ULAoiUh6zWYK+lkUiBn+d",
	"EhbU4EINv3edhARPrdI00KWyQlOdlxKBWCLjRHqMhgvF2DElqxQJXc4BjY6Qj6niNtP74jBcIIWF2jFA",
	"twSP6a8J8EWeeSJjHPUi/w+RqRYb610CNyuqAEczoMCxBIEwuroaHTXGdExfszBkdwIdDM+8Vrud2U8N",
	"CqO3CltGRVXs+r0m7HWbTQ9U/txtBV0P77b6Xrfb7/d63W6z2WytE8NHF2TW8juJgy+zHyEWEkUsMOTe",
	"wIr0Bq0vsSL32RM2UUGG4zqfPAyxl7mxvHAlnMF7p17tbtSfNyS4d65dJw4TjsOq2invRugsCTGvvMoN",
	"cfo0whTPgDcCP2oQtlMavKK2+WyuKF3wu0v61i4pqzX8rn2Tl1VMyk4qK4c/5KwKk9d7rcLgb+O+Upye",
	"wY3lvP/uz777s0f5s/wA5n3JB1Ssk5Xu6y9xgDW6bT2hff6gS/SKtdQVvtErHLpt7iTzWSu85VtiTjzK",
	"HpPCJ3kT4xncSPYRarzmpXqs9ZWD5ARu0/qomonUzMaYDqNYLpBhCCI0UHkr2OSYCD1cS4UdXpIEWPzt",
	"9pfol99++cffyemHq7vp3//61zqnyEEkoTnzqhzxcI4XyqvXGpNMGXV1XEclj7duTh4zYbXbktClwLlL",
	"BF0StnruXFizW0btwlgtWwVQTMD1WLoogCmhKW9KYzhMgQP1YUyVKzVm1Wd0SmYJxwXLVJaMSphXIxl5",
	"EGU2Gh0Zjq/igwVDPCaOUr5vjbNOGXxDAvEY35NZaevJz0Lsg44Yjq2ajemDjggJkGiyKLqHINEqUEYn",
	"k7pHmf72EuZrTfeKAVZkXScRwG9ucZjAQ2qkRiEzytJqFU8r6D2kVCoOfKfWXKtKVbkrg71Gnf5gRu5L",
	"bNvL2bSn2bIGGt6qoKyEYAB+iDmIMWUUEOMoYhx0+hDkyKOtf2a//+miiFDU2m6gA6QcbAiZWx9TNp2C",
	"Zl8iQKDCLNMHofYAKvmizh7mtF5C7aQMTwMNsT83K2UYIFzqM3Gz4HRMC6c/jAcaQBc9bKofw+w0bVFc",
	"iggdmamt9dy36D7A7fNCwFSR1wqTNIEJrfK8hs4a6Yc0oI4quaFKN1QKq7hQGme8JAj1VEiOCZXC5Jcw",
	"xUrY9ToGgjG1fqHItjSP8OvM+0O80E0jh0VYlvUv7S/a1IUVsE3JW3X+Y2qLGFqwxNHERTiOt6vmKX27",
	"ibPVIiJu1qiDUJxicq58u4Un11c5x9J0zHBQPDrXLTpCYgljOoGp0vEyekSYdExF9RBUwH+fw39dYMca",
	"TKq0L/bz1Ac7F0VBqBO4B6KardvIVVInMaHAXRRgiSdYgIv8MBES+PbjQ5+KxqYpThGPOt3NjhHLGOrH",
	"KG02Q1Od0ypbqRK43b3mLjrjbBJChI70oZnRlTeXl2fo4GwkTHCpM+D9jjmaQ+dp51qd2pS1Pj2Iq0L1",
	"Jokw9VRgo+kKn+IQU3uabtdEkhlO2H4OFWzaGp8+j2yM6TFepMRP+zq8bHpg0ZEMzSGMUQCTxHh/IsRy",
	"gWnj9q8liSOFuuXGGp6BWepZMcHXoSlzJAICM4Fj/6NimTFpk2Q2I3RWRWDDXrQsFU848bLgvQ6v9ARz",
	"iXdKNsxL5LMA0FaEpT8HkYbfRtLMiFJ5QPe/ZQAQKjvtfGNCJcxAH/za49KlUGPOuHTRvCw7IokizBcl",
	"2dC63BjTizlLwkARU3kGIqRKA7DPmSiKlUjnChxVFihReJOOvaohquJwjP05oVAQfb2domMDXSmdOhhq",
	"6uoOnMLbtMxEk0hZhaXOQHfp7NgttNK41RZMt6ZBznXOhxenV+eHw5vhP94cXF2YVeqO+13n4MfTc/P+",
	"9Ory5vT1zfnByU9DDcbo+OztUAGlX2cNUBrCdwejtwc/vlUDj4YHR29HJ2qzw+HwaHikzFqB2ssYbiq7",
	"FQtqG4CtPKfiVWdDa9z5UtZhY4pl1h6ZFybHyjVdhx0q51TuxcSEAjFbZVbvXon0gGLLFjgNHi6iSTRR",
	"XmXCWAiYushA6iLt3fTBxRRBQLRz+usUh8rxFBOXKfkEgQGoMlhnkqWxhBJJcLgjktkMhCzMKypB23Vo",
	"EoZqDZOO6oYDjdSNodbjwiXTRCRO6aZnDthXljDEEwgrNFYJ/9Vo5/DtyODKIiIlBC5SsfetsqWcRRpV",
	"Xei3EdTYufXjpOGzhMqxg/73v/8HjZ13fpygQ/NoyYMfnl2Zd8tF3CUjkNK7JDiGURXs/mMOOqwCGuhU",
	"Xehqt663LopIGunSZVprhxQ9rNsSBvNMEiAvchhR0D4V0ri4lsOlGoOVvNWHJ0dMepRJ47o1XSVDOGfI",
	"2kh72JgNKkxQTIkgYnzREOQ3uJlN0mcSqwCrobkvGpIAHzvV+CpbaH3Uq825BuQm77LBQUBMCndW0HtD",
	"lTLuf7s4PUEXRnWLmYcSy3RpXXDImLcVcDyVqN1sN71WW0nWqS46mW4m5Q40Y0taqtxYEseMS5H7heLW",
	"H2Fxx3ggBjYDjQglURK5KMKf9I8xtVVvFyn3oUcYsugx6U+Qvj72OE8N6wDNpYzFYEe3WHmGRA3GZzsa",
	"jR2LRvGtl5O0zJelZEKbNuV4lTr5TKXSWy2v1d82WqUAdwatvuah/cN1oiSUJA7hdFpkaDFyKFv0iiPQ",
	"IryZ3c/t0hLoh4ymEpIpkgrhYpPIF065XgmrrgWzj6lJn1K34KHXOjdV2mky1AHCKkaHQBfWxPufr1MT",
	"ne6mhaTQyf1ztk4qOWuXwmnabcGuXfMcBAuV5fRDAlR6ggSAVHoTKEx0QVFACP7KYrPdvVCcrNeuz1l6",
	"V5PBVQOo2BhyC2vRKm7ZKt5HWKCft5UlSrFb8sajacE8YmlMF/ya4FCY6W5h/CuRLYQ5qOFlxN7/fJ06",
	"eCJQhOP3BpDr99eYLgZqQTPTPBZuWofVqyk8dQiK6cJ4pXScFistpMJ6oSXJfYRVzvE1aRUtymXjITP6",
	"cHhlL1FVeF2nZoVG8y9r8ih7FBs8lds61K8JSPPjX7fHI6/0PK6/oznofFl/R+pMlxlhvOtDyrrcLFJC",
	"82dYeEYhY0y4UT4fS5gxTn4zMmnKoKHUVdHGmP7I5NyqCQ2K2mE1oVH1Jna9hTNwKMg7xj+W6z8FD7Ch",
	"zjzYBmIFzlNriZ3PpZuC9/Y8yVpWH1NGiY/Dhw6nqkJXXr9wB6MsheVhz9Ua8mCF7DDEQuQF/hoFbIzp",
	"IYsiRlO+EeqHSQADtK441hjTg0D5dxU6ScaV7VzYYi7yEyFVvK5QRRNYMKoMFwioraitbHjZPJyz1imv",
	"IJVrzKmZSU3fdiPnO6aIxfhX5emJ9oaYZ5WpQniukcnXNz5ax1xDg41Ak0Vp8EA59nfHA6TssYtMVOwi",
	"IRnHM3DRTCUAN0y4tnFdDT9MKT5AJNKjshKtm96GcpHVGjXhyPJlgEBfsnCRtcOFmXphw7VB/pqyQMVt",
	"ClPOQhSHWM1W6wIX2wqxy7nW4cSXCQd0izlRSKYhREGUtPiZ41dN6NQXLGm+oYH6ZZMDZ7Cnq1WaJFqA",
	"ifgonMF7ZSVi7BO50KN6zeym74Sxol8TgXN/rfIBP060zHB/TiRomJ2B82mvf9PvOq5j/OGgfW+OXIoC",
	"1aqxM49smirp1Pdeqd9Rr1TJiT+6T6o96PZeqk+qZNuf2idV7/z0mktdUaWx5Wao4qu1PVClwZVPAbxY",
	"N4DybvZ4/PGNAafGAejNkYcCZjQIc6FPuE2BIPElijBNlEI+3EwwvDt+03xiM0EpPM7Pr82BSXqUYXQ8",
	"xRfpGr5GShuGR5yBFqP6520+yLtLlrj99GpUSo9XokSnMS1XplDqkjepTj0iecobmx4IQXUjtRY0E0dL",
	"zGcgxdPPd29TKlbSqnKpOm8Reql6ddkIruxOcNw0qzSAX9fF9QL8hBO50GUwIxUTwBz4QWJkQ0Op3b1+",
	"nPNiLmVs7soROmXp1ULsS1OAWD4iPjo8znribBcZOjgbpf5Rd4HYgJ38BgG6wwslecamjWlJH01Hn60m",
	"0KB0rm9yJUKnHOdBU6G2ayNOtfU0d7hoSz0Y0jmmttNNRSZM4FBsZ3Dppcc0pbDHOAEq9SVlQWZUL/6n",
	"P6HzPOBTId8PPxS0W/zwwwAdmehcQhSH2h4qiAMy1TVDacN1Nl2FxJgitPXueEVe8HMyAU5BLWtTBFfb",
	"zkIqsG3AKvQlabAOVZgOQabSaUuQMC1A5Zi70mWiYNKcyGu4WlJD4gMVWm1s3HgQY38OqN1oOq6T8NDK",
	"khjs7Nzd3TWwfq0rpHau2Hk7OhyeXAy9dqPZmMsoLJxvOivESol9WgjJyxH3rsNioDgmzsDpNJqNrtUS",
	"Lfk7K9qRB5+dGcg6U6NdoBbdGM8I1dQLiZArW25FsRKdJe8qY6nvDNWRoaOhNoQeBc7AUc67plFWaGTy",
	"zzq9/yLvnX7fR7uy/AM/BXdTvFe7FFAtH9rqerS1b1q6tbJK5T5lwimKgWsYVmwc4U/G1ymPUdo7OxRq",
	"1Z6N55XwpnpfrIVXi9/LYL/WPFrBzCW+aXbp4wiDk7BI3s2Bm2ObRqWHE+Xn/qmnWqprVL4pVaHLclPo",
	"aq5cVz6Z1G42N7gUvtnt6VV99TX3qS8SnWhPkzBrdVCq2TXQ1G2SQb1T+EaRntJaP6V8fVtN6qyfVPpO",
	"TW8TyOq+yKJ9rGmusHq7QpR0TY2JGitzqAuaysZQuFvZbFwwKyoC8fJEdXQkVLKq9fzVqmsZr1A1ldVO",
	"NIAoZhKov6gzQwayujsBa+zQqU2oq6CusoGPUYeKBlQS20d+YuzahFYg5I8sWLykqqTfMyt+Le1+SVtb",
	"Lw9CRfhqOZLW2EWmx+GioMDPAuADX/ApdxBNWLBAaWsqMs7861mGbrO/fkbluy562v76aeUP2qlZ7fYG",
	"m5U+iaJndTcFsfw5mmeyesZMrLqeowfvPO6KqDGSIUio6yAKwZjLB+5llO2YmbKRHaujRT5kZ/VXJmtc",
	"b7fG1teqm0G1Tt2+kohvID/Z57OeT24MW1bLjbs+Kje3HFb4lckCESlWhNg/gfzqAtH817Du05SP/+by",
	"9RPI5zRKAw7zRaAyaB131MZyl5zMZsAFSsfa40BMzdfhVD5Ww7vGmP5UODBQcWDxbMC0NIcwM7VVtvLK",
	"3pKUn6cg/1FlPeNZnXV9pFh+DwXWqlwmb5sr3nOUX1ZXXSpn8OsqLd8rLF+lwiJqWHNeU1DBdFFzFGFO",
	"wW1dpbbRoQ756inft66hfK+drKmdPKlksnml5LlqIs9SC/m3LoF8w9LH2kDhe6WjEKY/JU55yRpCTbBQ",
	"/fLh4ysFGxUIvig2fnJB4PdWB9hIYkqfgH/h4sGTawaPKBW8jGg0v4n1++NWAmyLs1/3z1J0Y5uoHIeb",
	"ywdlqUn0B/P1NaNj4DNAZ7o/SLez7Xb2+9s6GjlhEsy1/0Lbmc7psxw/bwHY4sX2FuGW+yKEi5Y/QrCt",
	"e8DJg537ZYE2GL6ETG8SR0SKVJ4m/l9eOKb4NlplOiO/cUxhgMj+k8O/v44boa6NIMr9lk8rN6xqT6q9",
	"eWinE30BTNkIXRjQKb9YVYUo9hA9axWiMaanE91GVLjdW+kstCGnNnExh1vCEpGln7bN8ZtUMswtNP1P",
	"IdLMyc2/WCMZajWbq+H7KgWPl3Tm1Ybe7/WCcr2g5Bw3rResUOXnLh3Y25OjI0TE6osCdyQMs9sCiFFY",
	"XXQo9hA/segwOqq/STGmx4mQtl8SHZ1ceK1Wu5N/QSDCEm2F7A64jwUg3W1Hkwg48U3v4HwRz4GK7cpX",
	"BepvRNAs0N6gbvd7KHaUuru/brFjaeva+1pG1v8lix35ZXj7L1T+aBWP0r9gXI5XqhcpN4pfbI5bsnTr",
	"ctwHzcuafGD5f1B+Lbe4Vuj/WDluRZgKNwA0G4u9/++vFY+MdTZMNs3aOzgmO3lH9fX9/wUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
