// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Ft7c9s4kv8qKO5W2a4jZUq2/NBW6kpjKxntOrbWj73dGeVsiGxKmCEBDgDaVlL67lcNgC9JiTOJd2rr",
	"/rJF4tno/vWvu8FPXiSyXHDgWnmDT15OJc1AgzS/JiJl0XIcT6he4O8YVCRZrpng3sC7XQCRoEQhIyAs",
	"Bq5ZwkCSREiiF0By07tD3hdKkxkQSh5pymL3nIzPp1wvqCaR4ImQmSJakOFoEnR7PSLht4JJyHBdgykP",
	"SDc4OiDRgkoa4epIKvgcn1+IJ5ARVUBS0PjGJ7zIZuYfymOyWOYL4IoIni6xvVmM0lRq8sT0glDXr3oH",
	"PG6/IUK6Iafc8z14plmegjfw5qmY0TSghV4Edk+e7zGUTI7y8j1OM2yXOyl6vue2FXsDLQvwPRUtIKMo",
	"2ow+XwCfo5yPDnwvY7z82fVxPA0SR/7fn2nwMQxOP+y6f4IPn0L/qLsqn+/9958939PLHGdWWjI+91ar",
	"FU6tcsEVmIMdphJovBw9M2XPPRJcA9f4L83zlEUUD3n/F4Un/aneNOqApiz1Bk45rKzG52RnUxw7hNp5",
	"CNiJUDxKUx7h4sLo6PgoPAqDYzg9Co76EQRwEp4E0KVHJwez5PD0ZOb5ntJUF8obHIanvqeZNqK/LtVu",
	"YwK38+HF9Wh4/q/70T/HN7c33qop6j9LSLyB96f9WvX37Vu1P5JSSCuwtrJ/bsaV7/1A42v4rQClv1GS",
	"bxmkMdmRMBf3kYhhh2SoiVwYs4Es18u26I5PDw7j5ACCw9nRQXDYO50FszDpB7OT+KAfQtQ96kNLdGEt",
	"ujG3VijtkknD4ivpjS//MbwYn98Pr9/dvR9d3r6C/L4w7cr33go5Y3EM/Bsl+C9RkFgYiS3oIxBVJAmL",
	"GHBNcpAZU4oJbgAmB4lgQ/SCKSJykGbwtnhnveggPoR+kBzR4+DkNOwGsyiGIOn2Dg77R8f4pCXeg1q8",
	"k2o6EgNnENdSnYyu349vbsZXl/fno8vx6PwVxIoYjBaH4BtRDTEpFEgSC1C1NGoRfEECK98bc0QZmt6A",
	"fARp5/y28xhyUnB4ziHCJQGOREQUFVJCTJ4WLAWSSxGBUozPjbNwetE+iG58fBKGx2FwktDj4PgoToLk",
	"NDwNkt7s+PQwov3wNGocRL+t53YzRJnd2EU0Vfx2dH05vHgV1d4208r3LoV+Kwoefx/AbgXW6oANDLWl",
	"djrrHyVhnwZH8Uk/6B/O4iA+psdBHCb94x6Fg5Nj2lLfwy3AimMnZvGVyC6vbu/fXt1dnr8mnNbzrHzv",
	"juMmhWQf4VuF9g+DMg2TQK2PJBh6QlNFqISSXcRoDjRCNbTWULKZtjxp1wJCAP3kKEDrD+gsigNo4EFL",
	"nt1ansP2Qir/Xwn17nJ4d/vj6PJ2fDa8fRVIWJvSbMttd1Zo8kSt4uRSPLIYYqQ3TBFm8RnnNyI0nb8H",
	"AkrAv4a5IGrJNX0mjLe8XIJ+ry3rHpycdrvH3eA0oSfByXESBiHt0qAXnZ6G/Wh2FJ7GTVn3erWs63Wv",
	"G/vb4fhidH4/uR6dXV2ej2/HV5evIOiN+VbVmIZTVdJrdzOPSUnHSCLSVDwhDF6/PSPHJ+ExmUgxSyEj",
	"50aWyvBYQ4xPDzpTPuUTe3SKKC2LSBeywlhmmLRdE9Lw4WRMEsrSQoLqGPqaS4R8zSwPLE9rfY0/Fhnl",
	"ARIdOkuBwHOeUm6HVTlELGER2o51IRbXeQREJJb42/V3pvxmIYo0LnWN0AiHMEOurzSGR0hxaW6dNc3e",
	"ZEcvqfQmAW7q2Ppe7zj7rdgSwDBV77XlwXgEHXKnIClSbDrlWtLoVzxBPKgYZsV8zvh8fR9fSdqsWLyB",
	"V0gWSEjATLhtS6URbBze7e2E2JcEBdZchaGC1RSM64NePTTjGuZgXJezqRf0QhVZRuVy7dyJGa659a/h",
	"nPW+7IONY7oek0oc5WktS/rQnLpDbvHwmDJvIsoFZxFNp9yeIorEnQ0vMm/w8ybd9Ru+zl+PJXzvenRz",
	"dXd9Nrof/fPH4d0Nwra/FWN8b/jD1bV9f3V3e3/19v56ePlu5Pne3eX4/eRihNOZ1xUfwVfDfwzHF8Mf",
	"LrDh+Wh4fjG+xMnORqNz03jdafhbuOWH1gFs7vBr9WzVjFp/9tzZOt0rFeVD1U3MfoFI4zFa+rJ5kNeQ",
	"S1AIsYRycjUZkt2rHDhxdGc4B673yiRB6ZEt7uEzBorEkDBuiS+SBedbixQUKQyjNE4HD9qYZEQ5BlIq",
	"EjnEU64FiVliNqxJirijyO67i6sfhhfoDO9uRtd7qEOwNGQhozpaQEzonCKITLnT4nKulM4AuV8KkRbS",
	"ojU80rQwdJxxkksmJNNLImQM0uzkTkFsYGYm9ALpCdVAdidXN7d7pn+Rx/bJ8Pbsx70OueKukU9ipvKU",
	"Lu85zcCfciune5S+TXhUONlmOruAgBshYi6NXSBZZRGYwafcTuibNIn1y4q4Y8ItNBg6mYnYCQbkHEc2",
	"fuvg9Ghvm4exy77XLNti07csA6VplpOnBfBG0shAuu0aO3M2i0KjFoXOCx3YhA7umBZaoCeJaJouiQLd",
	"3GItcEXGN1fk5CjsEqv7NnWBK/souImSrJc9DNehuxf2joKwG4Snt91wcBAOwvCnpgmh7AKzRTQWGl/x",
	"dFmmeDbgrSWCdYlcmX9oSqxnBvQn1fsKZ20QoEheyFwoq+QzWNBHJnC7N0WeC6kVyaj8NRZP3G1Yb/FK",
	"I6sWap0yNxNwhEZSKEVompZqo0qtyKWIi8iSIP7IpODYxfObCa1eeHiyTRANTX7R1WCjjcxihfPLvDz9",
	"BW6XoUZjHIweTSbU7I/H+BbpyAxqqT7CukTemXCLrNHoSZnga+6r31/P1G1sEgzdie3+ElqkulSM9nb/",
	"ZwF6Ac3t4cYs39Dp0lCnR+iQc6bMgLYRgiGaIhd6ymvQiQtp6EgLH2OImEmDrG24paYzIVKgJhvA4q/n",
	"SmtHss1W8QCmnGVZoc2B0kSDtDbOBDd4S8bnJVYLZwd4pJaEQUweGZ3y3wqQy5pBEMGrQf5CWNIign4D",
	"BsgcOEiqUWLk7m58bnDhrWHfqpF3dnEpLkXwR9znpsi2p35fN4X7Io4Yv3Nf+h0TmsUxs2KbtDD4yxDk",
	"/Q2WAaoOkJwyiW7NRsbG8Vki7DTSuUDCeCQy1LDSFXam/LaluLUumrNniQEPs2RVDVz7FBNfPuvOlI/x",
	"BNd8Kg7YPtJtE6Em4iSNNU35mcgywd14v8LSFhMaSDVoIJiPrBmpu1+GI9gCOyCY3LN4YLNrtfrjO4eI",
	"g/IfA1X4QsKcCT4gcxBzSfMFQpR7iK81A1l3wl9kN5LM+DGzEh5TGfsEdNTZa+vfJ6+JtQOv3oJRnLk9",
	"10IFQJUOuoamgfQGXjl+TbMbhC3fWuWpMjX4ukR950CnXolC+5/KKsdq6hlt+AIMfMZHf9YWzcxfsMZq",
	"EVvNsmF5VcNXMsEG+doU3A3SzbbLJo3kyTpUfhYZp0ZbLD8dkCGOACaV3VT20kUbkS6Vhgw7IZVtdama",
	"G2Op41tU6xbDRqfSIrELBpLKyCqxIbID4jxlMC3C8AAwJJatuMquGeOVm9F1OyCpXm3K1LHllsc0md22",
	"eCclq7bQhRtyQnbrNoTJMG5bJCzrgiYnPuULNkd/W5FzwyRbu06YVNqI3yYVJeVzGJBu0A3D0NYku2E4",
	"IGfOqPat4CvPbJqE3aCPjW6cPbfe9kM72ABXGFRLqZs01by7NXTP6DPLUNw4jnE67ue2qL6KDbYXczEW",
	"M5GTE6SJlK2amoAC4fYZokKbJH6LsE95E4vrmu9GDtDIEyczIzpCVsZzJKfRr3RuCS0lDxll/MEEdsRU",
	"iiXoQnJFaBn3VKSGWBgju6gHTmTkQcIvpgLx4JMH60wgvneeRD5gvHImeOkzSSrmLCIZXaI5kNqZNtdh",
	"eeSDU0xiXlRbqqNOpuzOnQcsI7xGaFcVXjbRrJRBoRcfcejmZGTwhnyaeuXGpt6AIDatsN1n3ic0VbBC",
	"F/xpyglhPC90Bw2+I0UK5M0bMvVonDE+9aZ8ZRbTZDL9/sHRiyzXbuqboryUKu2E8ntDPder7UpQ3JQv",
	"SSZihLYaQ18vBOwPDvvfEQJu+F7few4o5EFVfjAXMYzXUoij6072nsUrhNM8LSRNGw7Q8z3F+LxIqazu",
	"HdQYa38HGeV0DrITR1mHiX3XalVlbC6YLWRv0ACbr85AKVRPNLSUKYwpK8Aych6jxGzcaGR50CM4ZMVo",
	"SAZ6IeJWhLktc8DhWd/ndA73WvwKW2LlW3xs1iFBSwaPZTIQexLsid5XgipSrTpknNhSurnPgfGSy28Y",
	"RinBxVEkEyZtYjtZy8YI08xlCqYUI6BGNOnK9DmVyupilLJ6T7UGwfKvjz9lP3386Z9/Z1e/3D0lf3/z",
	"xvscqajy880NGzGKZD035gj1WiWVINcDyajne0xDpl6qc7gIt9ZOKiVdbiQAq+Vt5vxWvqcgKtCH3eCg",
	"dg8zoBIkhtP4y8xmIk3zuBbAQuvcVlkYT0RZdKIR6uJmjWs0CXALKaNck+vRza0tdQhJjHqjLL6YWWR1",
	"BuP87H3Z4r0zjerY7aCWlmJb/D3iC8ojo7cE4yyhaKrI7nA02VvXcWXrA+VBBUKiZtikDptz30U1uNqz",
	"67vzhlMwW5msnbNZ15/+RP4GS/IWqC6kpRFvizTdOoBTFGvxZSzjskOmgVXVoA6xLTtHHA3KeDkm43M7",
	"TQrPDAlqwlLULFfwyFHcZlJsNKFSM5o6bFYuhUn2bbZwD5u0D88m5ReUxynjc2MzKYuAKwOD7grVMKfR",
	"AkivE3q+V8jU6Ysa7O8/PT11qHndEXK+7/qq/Yvx2ejyZhT0OmFnobO0UdXw2seNp+r53iNIZbXrsUvT",
	"fEG72EXkwGnOvIF30Ak7BzaeWBjF3m9a6hz0doNVtcIZZ6Ma4q9F59dCtWlcw1xtvs6c+dvytXFkRhkf",
	"bJeHRjLEzHA2ugiUXtq6nQR798XEvQ+NgOXNjuXgOw/mjctTvUGP9bDZFhn8DhlenpO1hmZxV26xjbWZ",
	"9d/Plo3VuSVUhFtFD2TXkZu99jsUo11FM0loupinjaxy2dYzZ2W1fxw74U9qx9i82fjzd7qSC6CP7mKW",
	"qwBiTIzhgmlrqoNWDGtO7IEkUmQucQqPTBTKwIN1rVqQOej2vF/pRcy1Q5Maa9w7rH1ns9a9wUbWhfHe",
	"hhQuXqocThVCIgc3VMnu1d4WMrzZvpvyBDDeanreglcY4xN35ma4ftgh5YQ2kmOKYCzT2RL9bNtlRp+t",
	"gBX7CK2NNqLH7wucNkVkrbFhXyYez/N0acviYKhRh1SZ+BoyZ8sNU3wYkHb5qWmRD5bh4yvD5NHkRlYq",
	"32vUru02s97Mr7zU6TNKaDf++xTwTGQZDRSgyaL/SR3vcXUpLSw6ktmyQ0Y0WriAwaaOp9w6bMvFdqiK",
	"dlB2OzjFToecN3Rvp4lFOwZp3YGZ6B8nMxIum+H/TTzC3w0k2nIyTazbhLMa5dbxzF/r2T6OxrvPSL1E",
	"3+32sD7C+oF8WLst3AvDr7gE9HW3aRoxxpYrNS2Gi7i98r1DO/u2QatV7jfu4Jou3Ze7tC6bmU4HL3eq",
	"L6qufK//NSvbdqnSMGV7d6LcdCOE03Ruwr7KeX0wUcG2qOzM6I0ilHB42qiZm5oKhsoOnjeKKktCp9xx",
	"QKqQkhq2Rx4Zte6LxQ9kreBi4HyjyDLlLvp+YmlalVrqSsuGd7Yrn9RJ2i9456ooukFXx+cbBahvWd2U",
	"XzfLnbtVHqDX2/vi1wc39YcE6dqHCPj6DCMYxm0NJP26LxWw36j8BuGbv0BYwwMWe9/6scHv/NLgg40W",
	"QekfRLx8Zdgov2RofkSx2gCr7r9l1rXss8uQ2isKRBXmFmlSpClKfQE0dp/QXAg78/YLTa46UA7TuH9a",
	"L7A+7jLkoTnruKedSGT7j939L5dAmnd9tn0d8h+Nsofh6cs92h+0YK9e7+Ve6zddXw/Tz1zCt4HL25F9",
	"5ddxZKOIZtUlBb0ln3puniPot4ruFb66ahLErMw5R5S7LFXBY8HBQZ5NpvfCQ3IpDFYB10TwhjYTs4aq",
	"Pl9P4eBVTbnSUvA5iQRXTGng0ZIEBCEky01u0IQMNHapqfJrsXJ56dKWu6a8nMlitIsyDs3aNDHX6Le5",
	"ESuLz7mRbadYN9lvfd62hfUcbsp+UpYdcNq23ZNdLoiDnb0/1D4OX+5RfYrweipuRV9p4eeIy9bEyLWN",
	"so0SK8bnaVUSmC0J04o4t2wU2+WL2XpeuUvewUZaeZuSvAP9b9KQ8I9zNS4xse5s/v/rGR7yS0qWUx1t",
	"ubtw55KQlNvvZKpaxdLd3cxb2Uqya5OUL6veIbFDb2gfGWtSKFDEpD2n3LC4v95cXZL3ODSZmKsvyC/L",
	"W5MdcoXssPocwwW5VEJZ3/rLlIuMad1+mUKiScGjBeVziG3K6YEXafqAkBulQGVF+F2/MpdY5mjdHnbf",
	"u9TsDXB3X8fms8xcS1GQJ8q1GdVMZn2BY9RGYjY5bg5hygV3KZBK5HVA4pxMcLvMwX7kiAH7Q9NszICB",
	"Geu/0IQeylWPqwsS5osAZWuu9ecTbr0NX+fKg7tszoWEmLCEKARnG9RTvcC/LDa/6hQH2a2HcNJdu5Kx",
	"txH4B6RRAd2CQFbSrwdCX0Ow1wX57yHbfyAClue5iX//udT1d0Lmt3HdVwJaBwdfxtpmkc8ob7O89/MH",
	"VE+LDFa1ba0GI5b9uqryoRp5M9Jv1a9atbxGhsRFtdWyVh9W/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
