// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Htrc+M2svZfQXG3yna9okzJli/amnpLseWJsh5ba8ubbKI5NkQ2JSQkwACgbc2U/vupBsCbpBlPZpzU",
	"1vlki8S10f30093gRy8UaSY4cK28/kcvo5KmoEGaX2ORsHA5isZUL/B3BCqULNNMcK/vTRZAJCiRyxAI",
	"i4BrFjOQJBaS6AWQzPRuk3e50mQGhJJHmrDIPSej8ynXC6pJKHgsZKqIFmQwHPudbpdI+D1nElJcV3/K",
	"fdLxjw5IuKCShrg6kgg+x+eX4glkSBWQBDS+aRGepzPzD+URWSyzBXBFBE+W2N4sRmkqNXliekGo61e+",
	"Ax413xAh3ZBT7rU8eKZploDX9+aJmNHEp7le+HZPXstjKJkM5dXyOE2xXeak6LU8t63I62uZQ8tT4QJS",
	"iqJN6fMl8DnK+eig5aWMFz87LRxPg8SR/+cX6n8I/NP3u+4f//3HoHXUWRXP9/7/372Wp5cZzqy0ZHzu",
	"rVYrnFplgiswBztIJNBoOXxmyp57KLgGrvFfmmUJCyke8v6vCk/6Y7Vp1AFNWeL1nXJYWY3Oyc6mOHYI",
	"tfMQsBOheJSmPMTFBeHR8VFwFPjHcHrkH/VC8OEkOPGhQ49ODmbx4enJzGt5SlOdK69/GJy2PM20Ef1N",
	"oXYbE7idDy5vhoPz/9wPfxrdTm69VV3Uf5cQe33vb/uV6u/bt2p/KKWQVmBNZf/UjKuW9x2NbuD3HJT+",
	"SkleMEgisiNhLu5DEcEOSVETuTBmA2mml03RHZ8eHEbxAfiHs6MD/7B7OvNnQdzzZyfRQS+AsHPUg4bo",
	"gkp0I26tUNolk5rFl9IbXf17cDk6vx/cvL17N7yavIL8PjPtquVdCDljUQT8KyX4H5GTSBiJLegjEJXH",
	"MQsZcE0ykClTigluACYDiWBD9IIpIjKQZvCmeGfd8CA6hJ4fH9Fj/+Q06PizMAI/7nQPDntHx/ikId6D",
	"SrzjcjoSAWcQVVIdD2/ejW5vR9dX9+fDq9Hw/BXEihiMFofgG1INEckVSBIJUJU0KhF8RgKrljfiiDI0",
	"uQX5CNLO+XXnMeAk5/CcQYhLAhyJiDDMpYSIPC1YAiSTIgSlGJ8bZ+H0onkQnej4JAiOA/8kpsf+8VEU",
	"+/FpcOrH3dnx6WFIe8FpWDuIXlPP7WaIMruxi6ir+GR4czW4fBXV3jbTquVdCX0hch59G8BuBdbygA0M",
	"NaV2OusdxUGP+kfRSc/vHc4iPzqmx34UxL3jLoWDk2PaUN/DLcCKY8dm8aXIrq4n9xfXd1fnrwmn1Tyr",
	"lnfHcZNCsg/wtUL7t0GZmkmg1ocSDD2hiSJUQsEuIjQHGqIaWmso2ExTnrRjAcGHXnzko/X7dBZGPtTw",
	"oCHPTiXPQXMhpf8vhXp3NbibfD+8mozOBpNXgYS1Kc223HZnuSZP1CpOJsUjiyBCesMUYRafcX4jQtP5",
	"WyCgAPwbmAuillzTZ8J4w8vF6Peasu7CyWmnc9zxT2N64p8cx4Ef0A71u+HpadALZ0fBaVSXdbdbybpa",
	"97qxXwxGl8Pz+/HN8Oz66nw0GV1fvYKgN+ZblWMaTlVKr9nNPCYFHSOxSBLxhDB4c3FGjk+CYzKWYpZA",
	"Ss6NLJXhsYYYnx60p3zKx/boFFFa5qHOZYmxzDBpuyak4YPxiMSUJbkE1Tb0NZMI+ZpZHlic1voav89T",
	"yn0kOnSWAIHnLKHcDqsyCFnMQrQd60IsrvMQiIgt8bfrb0/57ULkSVToGqEhDmGGXF9pBI+Q4NLcOiua",
	"vcmOXlLpTQJc17H1vd5x9nu+JYBhqtprw4PxENrkTkGcJ9h0yrWk4W94gnhQEczy+Zzx+fo+vpC0WbF4",
	"fS+XzJcQg5lw25YKI9g4vMlkTOxLggKrr8JQwXIKxvVBtxqacQ1zMK7L2dQLeqHyNKVyuXbuxAxX3/qX",
	"cM5qX/bBxjHdjEgpjuK0lgV9qE/dJhM8PKbMm5BywVlIkym3p4gicWfD89Tr/7JJd1s1X9dajyVa3s3w",
	"9vru5mx4P/zp+8HdLcJ2ayvGtLzBd9c39v313eT++uL+ZnD1dui1vLur0bvx5RCnM69LPoKvBv8ejC4H",
	"311iw/Ph4PxydIWTnQ2H56bxutNobeGW7xsHsLnDL9WzVT1q/cVzZ+t0r1CU92U3MfsVQo3HaOnL5kHe",
	"QCZBIcQSysn1eEB2rzPgxNGdwRy43iuSBIVHtriHzxgoEkHMuCW+SBacb80TUCQ3jNI4HTxoY5Ih5RhI",
	"qVBkEE25FiRisdmwJgnijiK7by+vvxtcojO8ux3e7KEOwdKQhZTqcAERoXOKIDLlTouLuRI6A+R+CYRa",
	"SIvW8EiT3NBxxkkmmZBML4mQEUizkzsFkYGZmdALpCdUA9kdX99O9kz/PIvsk8Hk7Pu9NrnmrlGLRExl",
	"CV3ec5pCa8qtnO5R+jbhUeJkk+nsAgJuiIi5NHaBZJWFYAafcjthy6RJrF9WxB0TbqHG0MlMRE4wIOc4",
	"svFbB6dHe9s8jF32vWbpFpuesBSUpmlGnhbAa0kjA+m2a+TM2SwKjVrkOsu1bxM6uGOaa4GeJKRJsiQK",
	"dH2LlcAVGd1ek5OjoEOs7tvUBa7sg+AmSrJe9jBYh+5u0D3yg44fnE46Qf8g6AfBz3UTQtn5ZotoLDS6",
	"5smySPFswFtDBOsSuTb/0IRYzwzoT8r3Jc7aIECRLJeZUFbJZ7Cgj0zgdm/zLBNSK5JS+VsknrjbsN7i",
	"lYZWLdQ6Za4n4AgNpVCK0CQp1EYVWpFJEeWhJUH8kUnBsYvXqie0usHhyTZB1DT5RVeDjTYyiyXOL7Pi",
	"9Be4XYYajXEwejQZU7M/HuFbpCMzqKT6COsSeWvCLbJGo8dFgq++r15vPVO3sUkwdCey+4tpnuhCMZrb",
	"/XEBegH17eHGLN/QydJQp0dok3OmzIC2EYIhmiIXesor0IlyaehIAx8jCJlJg6xtuKGmMyESoCYbwKIv",
	"50prR7LNVvEAppylaa7NgdJYg7Q2zgQ3eEtG5wVWC2cHeKSWhEFEHhmd8t9zkMuKQRDBy0H+QVjcIIKt",
	"GgyQOXCQVKPEyN3d6NzgwoVh36qWd3ZxKS5F8Efc56bItqd+XzeF+yKOGL9zX/gdE5pFEbNiGzcw+PMQ",
	"5P0Tlj6qDpCMMoluzUbGxvFZIuw00rlAwngoUtSwwhW2p3zSUNxKF83Zs9iAh1myKgeufIqJL591e8pH",
	"eIJrPhUHbB7ptolQE3GS2pqm/EykqeBuvN9gaYsJNaTq1xCshawZqXurCEewBXZAMLlnUd9m1yr1x3cO",
	"EfvFPwaq8IWEORO8T+Yg5pJmC4Qo9xBfaway6oS/yG4omfFjZiU8ojJqEdBhe6+pfx+9Otb2vWoLRnHm",
	"9lxz5QNV2u8YmgbS63vF+BXNrhG2bGuVp8zU4OsC9Z0DnXoFCu1/LKocq6lntOEzMPAJH/1JWzQzf8Ya",
	"y0VsNcua5ZUNX8kEa+RrU3C3SDebLpvUkifrUPlJZJwabbH8tE8GOAKYVHZd2QsXbUS6VBpS7IRUttGl",
	"bG6MpYpvUa0bDBudSoPELhhIKkOrxIbI9onzlP40D4IDwJBYNuIqu2aMV26HN82ApHy1KVPHlhse02R2",
	"m+IdF6zaQhduyAnZrdsQJsO4bZGwqAuanPiUL9gc/W1Jzg2TbOw6ZlJpI36bVJSUz6FPOn4nCAJbk+wE",
	"QZ+cOaPat4IvPbNpEnT8Hja6dfbceNsL7GB9XKFfLqVqUlfzztbQPaXPLEVx4zjG6bif26L6MjbYXszF",
	"WMxETk6QJlK2amoCCoTbZwhzbZL4DcI+5XUsrmq+GzlAI0+czIzoCFkRz5GMhr/RuSW0lDyklPEHE9gR",
	"UymWoHPJFaFF3FOSGmJhjOyiHjiRkQcJv5oKxEOLPFhnAtG98yTyAeOVM8ELn0kSMWchSekSzYFUzrS+",
	"DssjH5xiEvOi3FIVdTJld+48YBHh1UK7svCyiWaFDHK9+IBD1ycj/Tfk49QrNjb1+gSxaYXtPvE+pomC",
	"Fbrgj1NOCONZrtto8G0pEiBv3pCpR6OU8ak35SuzmDqT6fUOjl5kuXZTXxXlJVRpJ5Q/Guq5Xk1XguKm",
	"fElSESG0VRj6eiFgr3/Y+4YQcMP3trxnn0Lml+UHcxHDeC2FOLruZO9ZtEI4zZJc0qTmAL2Wpxif5wmV",
	"5b2DCmPtbz+lnM5BtqMwbTOx71qtyozNJbOF7A0aYPPVKSiF6omGljCFMWUJWEbOI5SYjRuNLA+6BIcs",
	"GQ1JQS9E1Igwt2UOODzr+4zO4V6L32BLrDzBx2YdErRk8FgkA7EnwZ7ofSWoPNGqTUaxLaWb+xwYL7n8",
	"hmGUElwcRVJh0ia2k7VsjDDNXKZgSjECqkWTrkyfUamsLoYJq/ZUaRAsf3j8Of35w88//Ytd/3r3FP/r",
	"zRvvU6SizM/XN2zEKOL13Jgj1GuVVIJcDySjXstjGlL1Up3DRbiVdlIp6XIjAVgubzPnt2p5CsIcfdgt",
	"Dmr3MAMqQWI4Xf26KMzmhx8n3rpn/+HHiZO3mGnKOLpiKVKbzRU8ZnNT8cARiSuFSM9VXkwMa6aoRLvQ",
	"OrP1G8ZjUZSzaIhavlk9G459FE7CKNfkZng7sUUUIYkxHJTyZ3OWrMqNnJ+9K1q8c0ZXKpQd1BJebIu/",
	"h3xBeWgsAjeWCUUTRXYHw/HeuvUoW3koVMAXEnXOpovYnLdcvISrPbu5O6+5G7OV8ZoGmXX97W/kn7Ak",
	"F0B1Li1BuciTZOsATgUtlhRRkss7mQbWCPwqeLe8HxHaLyLxiIzO7TQJPDOkvjFLUGddKSVDcZtJsdGY",
	"Ss1o4lBfueQo2bd5yD1s0jw8m+5fUB4ljM+NNSYsBK4MwLrLWYOMhgsg3XbgtbxcJk5fVH9//+npqU3N",
	"67aQ833XV+1fjs6GV7dDv9sO2gudJrV6idc8bjxVr+U9glRWux47NMkWtINdRAacZszrewftoH1gI5WF",
	"MZn9OgbMQW+HAlUpnHFjqib+SnStSqg2QWw4sc0EmjO/KF4bF2mU8cF2eailWcwMZ8NLX+mlrQhKsLdq",
	"TET9UAuF3uxYdr/zYN64DNgb9IUPm20xNtghg6tzstbQLO7aLba2NrP++9mytjq3hJLKq/CB7DratNd8",
	"h2K0q6inH00X87SWry7aeuasrPaPIif8ceVy63cmf/lGJ3UJ9NFd+XK1RYy2MRAxbU3d0YphzT0+VBiZ",
	"SXhkIlcGHqzT1oLMQTfn/UL/ZC40mqRb7UZj5ZXrVfQNnrMujHc2WHGRWOnKyuAU2b0hYXav9h6SYeT2",
	"3ZTHgJFc3afnvMSYFnFnbobrBW1STGhjRKYIRkntLXHVtl2m9NkKWLEP0NhoLS79tpBsU0TWGmv2ZSL9",
	"LEuWtuAOhnS1SZnjryBzttwwxYc+aRa26hb5YGMHfGViBDS5oZXKtxq1a7vNrDczNy91+oQS2o3/MQU8",
	"E2lKfQVosuh/EseoXMVLC4uOZLZskyENFy4UsUnpKbcO27K8HarCHZTdDk6x0ybnNd3bqWPRjkFad2Am",
	"r4CTGQkXzfD/Oh7h7xoSbTmZOtZtwlmFcut41lrr2TyO2rtPSL1A3+32sD7C+oG8X7uH3A2CL7he9GX3",
	"dGrRy5bLOg3ujLi9anmHdvZtg5ar3K/d7jVdOi93aVxjM50OXu5UXYFdtbzel6xs23VNw8HtrYxi07Xg",
	"UNO5CShL5/XexBvb4r0zozeKUMLhaaMab6o1GIQ7eN4o1ywJnXLHAalCSmrYHnlk1LovFj2QtVKOgfON",
	"8s2Uu7j+iSVJWcSpajgb3tmufFylfz/jncty6wZdHZ1vlLa+ZnVTflMvpO6WGYZud++z3zXcVp8oJGuf",
	"OODrM4xgGLfVleTLvoHAfsPi64av/rZhDQ9Y5H3tZwx/8BuG9zYOBaW/E9HylWGj+Eai/nnGagOsOn/K",
	"rGt5bZd7tZcfiMrN/dQ4TxKU+gJo5D7OuRR25u1XpVzdoRimdrO1WmB13EXIQzPWdk/boUj3Hzv7ny+u",
	"1G8Rbfvu5L8aZQ+D05d7ND+VwV7d7su91u/Qvh6mn7lUcg2XtyP7qlXFkbXynFWXBPSWTO25eY6g3yjn",
	"l/jq6lQQsSKbHVLu8l85jwQHB3k2Td8NDsmVMFgFXBPBa9pMzBrKyn81hYNXNeVKS8HnJBRcMaWBh0vi",
	"E4SQNDNZRxMy0MglvYrv0IrlJUtbSJvyYiaL0S7KODRr08Rc0N/mRqwsPuVGtp1i1WS/8eHcFtZzuCn7",
	"cVHQwGmbdk92uSAOdvb+Uvs4fLlH+ZHD66m4FX2phZ8iLlsTIzc2yjZKrBifJ2WxYbYkTCvi3LJRbJeJ",
	"ZusZ6w55CxsJ621K8hb0n6QhwV/nalxiYt3Z/N/XMzzkl5QsozrcciviziUhKbdf4JRVkKW7FZo1spVk",
	"1yYpX1a9Q2KH3tA+MtIkV6CISXtOuWFxP9xeX5F3ODQZm0s1yC+L+5htco3ssPzQwwW5VEJROfvHlIuU",
	"ad18mUCsSc7DBeVziGzK6YHnSfKAkBsmQGVJ+F2/IpdY5GjdHnbfudTsLXB3E8jms8xcS5GTJ8q1GdVM",
	"Zn2BY9RGYjY5bg5hygV3KZBS5FVA4pyMP1lmYD+fxID9oW42ZkDfjPX/0IQeilWPyqsX5lsDZau51YcZ",
	"br01X+cKj7tszoWEiLCYKARnG9RTvcC/LDK/qhQH2a2GcNJdu+yxtxH4+6RWW92CQFbSrwdCX0Kw1wX5",
	"55DtvxABi/PcxL//Xur6ByHz67juKwGtg4PPY229fGiUt144/OU9qqdFBqvatlaDEct+VVV5X468Gek3",
	"6leNWl4tQ+Ki2nJZq/er/w0AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
